/*
#define CRYPTO_KEYBYTES 16
#define CRYPTO_NSECBYTES 0
#define CRYPTO_NPUBBYTES 32
#define CRYPTO_ABYTES 16
#define CRYPTO_NOOVERLAP 1
*/

#include "schwaemm.h"

#define CRYPTO_KEYBYTES SCHWAEMM_KEY_BYTES
#define CRYPTO_NSECBYTES 0
#define CRYPTO_NPUBBYTES SCHWAEMM_NONCE_BYTES
#define CRYPTO_ABYTES SCHWAEMM_TAG_BYTES
#define CRYPTO_NOOVERLAP 1
